name: Build package
on:
  push:
    branches:
    - main
jobs:
  macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.7
    - name: Set up Ruby 2.4
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4
    - name: Set up certificates
      env:
        ITERATIVE_APPLICATION_CERT: ${{ secrets.ITERATIVE_APPLICATION_CERT }}
        ITERATIVE_APPLICATION_CERT_PASS: ${{ secrets.ITERATIVE_APPLICATION_CERT_PASS }}
        ITERATIVE_INSTALLER_CERT: ${{ secrets.ITERATIVE_INSTALLER_CERT }}
        ITERATIVE_INSTALLER_CERT_PASS: ${{ secrets.ITERATIVE_INSTALLER_CERT_PASS }}
      run: |
        echo $ITERATIVE_APPLICATION_CERT | base64 -d > application_cert.p12
        echo $ITERATIVE_INSTALLER_CERT | base64 -d > installer_cert.p12
        security create-keychain -p 123456 build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p 123456 build.keychain
        security import application_cert.p12 -k build.keychain -P $ITERATIVE_APPLICATION_CERT_PASS -T /usr/bin/codesign
        security import installer_cert.p12 -k build.keychain -P $ITERATIVE_INSTALLER_CERT_PASS -T /usr/bin/productsign
        security set-key-partition-list -S 'apple-tool:,apple:,codesign:,productsign:' -s -k 123456 build.keychain
        security find-identity -v
    - name: Install requirements
      run: |
        pip install wheel
        pip install -r requirements.txt
        brew install mitchellh/gon/gon
    - name: Download dvc pkg
      run: python download.py
    - name: Install dvc requirements
      run: |
        # available lxml (webdav dependency) wheels are built with an old
        # SDK, which breaks osxpkg notarization. Building from scratch
        # instead.
        pip install ./dvc[all] --no-binary lxml
        pip install -r dvc/scripts/build-requirements.txt
        gem install --no-document fpm
    - name: Build and sign
      env:
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      run: python dvc/scripts/build.py osxpkg --sign-application --application-id 62687162A75C39558A9EA17B57E8C65306BABE92 --sign-installer --installer-id 374191642324A98B1D9835CCD256EDEE2C710051 --notarize --apple-id-username kupruser@gmail.com --apple-id-password $APPLE_ID_PASSWORD
    - name: Upload
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: python upload.py dvc/scripts/fpm/dvc-*.pkg
