name: Build package
on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.7
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        brew install mitchellh/gon/gon
    - name: Get latest dvc version
      id: latest
      shell: bash
      run: |
        version=$(./latest.sh)
        echo "::set-output name=version::$version"
    - name: Download dvc pkg
      run: python -m wget https://github.com/iterative/dvc/releases/download/${{ steps.latest.outputs.version }}/dvc-${{ steps.latest.outputs.version }}.pkg
    - name: Setup certificates
      env:
        ITERATIVE_APPLICATION_CERT: ${{ secrets.ITERATIVE_APPLICATION_CERT }}
        ITERATIVE_APPLICATION_CERT_PASS: ${{ secrets.ITERATIVE_APPLICATION_CERT_PASS }}
        ITERATIVE_INSTALLER_CERT: ${{ secrets.ITERATIVE_INSTALLER_CERT }}
        ITERATIVE_INSTALLER_CERT_PASS: ${{ secrets.ITERATIVE_INSTALLER_CERT_PASS }}
      run: |
        echo $ITERATIVE_APPLICATION_CERT | base64 > application_cert.p12
        echo $ITERATIVE_INSTALLER_CERT | base64 > installer_cert.p12
        security create-keychain -p 123456 build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p 123456 build.keychain
        security import application_cert.p12 -k build.keychain -P ITERATIVE_APPLICATION_CERT_PASS -T /usr/bin/codesign
        security import installer_cert.p12 -k build.keychain -P ITERATIVE_INSTALLER_CERT_PASS -T /usr/bin/productsign
        security set-key-partition-list -S 'apple-tool:,apple:,codesign:,productsign:' -s -k 123456 build.keychain
        security find-identity -v
    - name: Sign
      run: python sign.py dvc-${{ steps.latest.outputs.version }}.pkg
    - name: Notarize
      env:
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      run: python notarize.py dvc-${{ steps.latest.outputs.version }}.pkg
    - name: Upload
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: python upload.py dvc-${{ steps.latest.outputs.version }}.pkg
