name: Build package
on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.7
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        brew install mitchellh/gon/gon
    - name: Get latest dvc version
      id: latest
      shell: bash
      run: |
        version=$(./latest.sh)
        echo "::set-output name=version::$version"
    - name: Download dvc pkg
      run: python -m wget https://github.com/iterative/dvc/releases/download/${{ steps.latest.outputs.version }}/dvc-${{ steps.latest.outputs.version }}.pkg
    - name: Sign
      env:
        OSXPKG_ITERATIVE_CERTIFICATE: ${{ secrets.OSXPKG_ITERATIVE_CERTIFICATE }}
        OSXPKG_ITERATIVE_CERTIFICATE_PASS: ${{ secrets.OSXPKG_ITERATIVE_CERTIFICATE_PASS }}
      run: python sign.py dvc-${{ steps.latest.outputs.version }}.pkg
    - name: Notarize
      env:
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      run: python notarize.py
    - name: Upload
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: python upload.py dvc-${{ steps.latest.outputs.version }}.pkg
