name: Build package
on: [pull_request]
permissions:
  contents: read
  id-token: write
jobs:
  macos:
    runs-on: macos-11
    environment: aws
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        path: dvc
        repository: iterative/dvc
        ref: "2.43.1"
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: pip
        cache-dependency-path: |
          requirements.txt
          dvc/pyproject.toml
          dvc/scripts/build-requirements.txt
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Install fpm
      run: gem install --no-document fpm

    - name: Install deps
      run: |
        pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt
        pip install ./dvc[all]
        pip install -r dvc/scripts/build-requirements.txt

    - name: Install requirements
      run: brew install mitchellh/gon/gon
    - name: Build
      run: python dvc/scripts/build.py osxpkg
